import "./globals.css";

import Header from "./components/Header";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import classNames from "./utils/classNames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, "bg-white")}>
        <Header />
        <main className="w-full h-full py-10 mx-auto bg-white max-w-7xl ">
          {children}
        </main>
      </body>
    </html>
  );
}
